language: node_js

node_js:
  - "lts/*"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile

jobs:
  include:
    - stage: test
      script: yarn test && yarn build
      script: yarn test:unit --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

cache:
  yarn: true
  directories:
    - "node_modules"
